name: CI Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js セットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. 依存関係インストール
      - name: Install dependencies
        run: npm ci

      # 4. ビルド
      - name: Build project
        run: npm run build

      # 5. Firebase CLI インストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 6. Firebase サービスアカウント JSON をファイル化
      - name: Setup Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" > ${{ github.workspace }}/firebase-key.json

      # 7. Firebase Hosting デプロイ
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: npx firebase deploy --only hosting --project indiegame-hub
